// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdRoE9E_Th7TDvReGyv9HqaczlU7wuLE0',
    appId: '1:62919950123:web:d97d54353d0cb02df90f6e',
    messagingSenderId: '62919950123',
    projectId: 'bible-62ac2',
    authDomain: 'bible-62ac2.firebaseapp.com',
    storageBucket: 'bible-62ac2.firebasestorage.app',
    measurementId: 'G-CDRGKT8Q9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdRoE9E_Th7TDvReGyv9HqaczlU7wuLE0',
    appId: '1:62919950123:web:d97d54353d0cb02df90f6e',
    messagingSenderId: '62919950123',
    projectId: 'bible-62ac2',
    storageBucket: 'bible-62ac2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdRoE9E_Th7TDvReGyv9HqaczlU7wuLE0',
    appId: '1:62919950123:web:d97d54353d0cb02df90f6e',
    messagingSenderId: '62919950123',
    projectId: 'bible-62ac2',
    storageBucket: 'bible-62ac2.firebasestorage.app',
    iosBundleId: 'com.example.bible',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdRoE9E_Th7TDvReGyv9HqaczlU7wuLE0',
    appId: '1:62919950123:web:d97d54353d0cb02df90f6e',
    messagingSenderId: '62919950123',
    projectId: 'bible-62ac2',
    storageBucket: 'bible-62ac2.firebasestorage.app',
    iosBundleId: 'com.example.bible',
  );
}